### ISSUE TITLE
Failed to load the backbonejs-snippets package

### ISSUE THREAD

**Issue by thibmaek** [d1b1/atom-backbonejs#3]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 0.190.0
**System**: Mac OS X 10.10.2
**Thrown From**: [backbonejs-snippets](https://github.com/d1b1/atom-backbonejs) package, v0.4.1
### Stack Trace

Failed to load the backbonejs-snippets package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at __extends (/Users/thibaultmaekelbergh/Dropbox/Mackup/.atom/packages/backbonejs-snippets/lib/backbonejs-snippets-view.coffee:4:199)
    at /Users/thibaultmaekelbergh/Dropbox/Mackup/.atom/packages/backbonejs-snippets/lib/backbonejs-snippets-view.coffee:9:5
    at Object.<anonymous> (/Users/thibaultmaekelbergh/Dropbox/Mackup/.atom/packages/backbonejs-snippets/lib/backbonejs-snippets-view.coffee:52:5)
    at Object.<anonymous> (/Users/thibaultmaekelbergh/Dropbox/Mackup/.atom/packages/backbonejs-snippets/lib/backbonejs-snippets-view.coffee:54:4)
    at Module._compile (module.js:452:26)
    at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "jslint",
      "emmet",
      "unregistered",
      "compass",
      "quippet",
      "autocomplete-paths",
      "autocomplete-plus"
    ],
    "themes": [
      "yeti-ui",
      "kimbie-light"
    ],
    "ignoredNames": [
      "node_modules",
      ".DS_Store",
      "npm-debug.log"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
Atom-Syntax-highlighting-for-Sass, v0.5.0
atom-bootstrap3, v1.2.0
atom-html-preview, v0.1.6
atom-spotify, v1.2.0
atom-terminal, v0.7.0
backbonejs-snippets, v0.4.1
close-tags, v0.2.0
compare-files, v0.4.1
editor-stats, v0.17.0
editorconfig, v0.3.3
error-status, v0.3.3
file-icons, v1.5.3
git-log, v0.3.0
git-plus, v4.4.12
gulp-helper, v2.0.0
gulp-snippets, v0.6.1
iTunes, v0.2.0
jsonlint, v1.0.2
kimbie-light, v1.0.1
language-swift, v0.3.0
laravel, v0.4.2
linter, v0.12.0
linter-flow, v0.1.4
linter-jshint, v0.1.1
linter-php, v0.0.12
linter-scss-lint, v0.0.14
open-in, v3.1.0
open-in-browser, v0.4.3
path, v0.4.1
remote-edit, v1.7.2
remote-sync, v2.4.1
ssh-config, v0.10.0
swift-playground, v0.2.0
travis-ci-status, v0.13.0
uglify, v1.2.0
weather-package, v1.5.1
web-browser, v1.4.3
yeti-ui, v0.1.6

# Dev
No dev packages
```

**Comment by mcarpenterjr** [comment]
[Enter steps to reproduce below:]
1. Launch Atom. Pretty sure this is a result of the recent ATOM update.

**Atom Version**: 1.1.0
**System**: Microsoft Windows 10 Pro
**Thrown From**: [backbonejs-snippets](https://github.com/d1b1/atom-backbonejs) package, v0.4.1

### Stack Trace

Failed to load the backbonejs-snippets package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at __extends (C:\Users\Mark N Carpenter Jr\.atom\packages\backbonejs-snippets\lib\backbonejs-snippets-view.coffee:1:1)
    at C:\Users\Mark N Carpenter Jr\.atom\packages\backbonejs-snippets\lib\backbonejs-snippets-view.coffee:5:3
    at Object.<anonymous> (C:\Users\Mark N Carpenter Jr\.atom\packages\backbonejs-snippets\lib\backbonejs-snippets-view.coffee:5:3)
    at Object.<anonymous> (C:\Users\Mark N Carpenter Jr\.atom\packages\backbonejs-snippets\lib\backbonejs-snippets-view.coffee:1:1)
    at Module._compile (module.js:428:26)
    at Object.defineProperty.value [as .coffee] (C:\Users\Mark N Carpenter Jr\AppData\Local\atom\app-1.1.0\resources\app.asar\src\compile-cache.js:169:21)
    at Module.load (module.js:353:32)
    at Function.Module._load (module.js:308:12)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
```

### Commands

```
```

### Config

``` json
{
  "core": {
    "autoHideMenuBar": true,
    "projectHome": "F:\\wamp\\www",
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

``` coffee
# User
angularjs, v0.3.3
atom-beautify, vundefined
autocomplete-emojis, v2.2.2
autocomplete-jquery-mobile, v0.2.2
autocomplete-php, v0.3.7
autocomplete-python, v0.9.4
backbonejs-snippets, v0.4.1
cdn-libs, v0.0.6
codeigniter, v0.2.0
color-picker, v2.0.13
colorful-json, v1.0.0
emmet, v2.3.13
javascript-snippets, v1.0.0
jquery-snippets, v11.0.0
linter, v1.10.0
linter-jshint, v1.2.1
minimap, v4.15.2
pigments, v0.18.1
seti-icons, v0.4.5
travis-ci-status, v0.18.0

# Dev
No dev packages
```

**Comment by fipo** [comment]
[Enter steps to reproduce below:]
1. Launch Atom

**Atom Version**: 1.4.0
**System**: Mac OS X 10.11.2
**Thrown From**: [backbonejs-snippets](https://github.com/d1b1/atom-backbonejs) package, v0.4.1

### Stack Trace

Failed to load the backbonejs-snippets package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at __extends (/Users/fipo/.atom/packages/backbonejs-snippets/lib/backbonejs-snippets-view.coffee:1:1)
    at /Users/fipo/.atom/packages/backbonejs-snippets/lib/backbonejs-snippets-view.coffee:5:3
    at Object.<anonymous> (/Users/fipo/.atom/packages/backbonejs-snippets/lib/backbonejs-snippets-view.coffee:5:3)
    at Object.<anonymous> (/Users/fipo/.atom/packages/backbonejs-snippets/lib/backbonejs-snippets-view.coffee:1:1)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/fipo/.atom/packages/backbonejs-snippets/lib/backbonejs-snippets.coffee:1:26)
    at Object.<anonymous> (/Users/fipo/.atom/packages/backbonejs-snippets/lib/backbonejs-snippets.coffee:1:1)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:721:27)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:117:28
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at Package.module.exports.Package.load (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:106:12)
    at PackageManager.module.exports.PackageManager.loadPackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:443:14)
    at PackageManager.module.exports.PackageManager.loadPackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:393:14)
    at AtomEnvironment.module.exports.AtomEnvironment.startEditorWindow (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:684:21)
    at module.exports (/Applications/Atom.app/Contents/Resources/app.asar/src/initialize-application-window.js:28:10)
    at setupWindow (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:86:5)
    at window.onload (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:41:9)
```

### Commands

```
```

### Config

``` json
{
  "core": {
    "disabledPackages": [
      "highlight-selected",
      "vim-mode"
    ],
    "packagesWithKeymapsDisabled": [
      "sort-lines"
    ],
    "projectHome": ""
  }
}
```

### Installed Packages

``` coffee
# User
atom-jasmine, v0.8.1
backbonejs-snippets, v0.4.1
language-cjsx, v0.3.0
language-javascript-jsx, v0.3.7
language-slim, v0.5.0
linter, v1.11.3
linter-coffeelint, v1.1.2
linter-csslint, v1.2.0
linter-jshint, v1.2.2
linter-jsxhint, v0.1.2
linter-rubocop, v0.4.7
linter-scss-lint, v2.5.0
sync-settings, v0.6.0
tablr, v0.10.0
trailing-spaces, v0.3.2

# Dev
No dev packages
```

**Comment by LaurentiLM** [comment]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.5.4
**System**: Mac OS X 10.11.4
**Thrown From**: [backbonejs-snippets](https://github.com/d1b1/atom-backbonejs) package, v0.4.1

### Stack Trace

Failed to load the backbonejs-snippets package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at __extends (/Users/Laurent/.atom/packages/backbonejs-snippets/lib/backbonejs-snippets-view.coffee:1:1)
    at /Users/Laurent/.atom/packages/backbonejs-snippets/lib/backbonejs-snippets-view.coffee:5:3
    at Object.<anonymous> (/Users/Laurent/.atom/packages/backbonejs-snippets/lib/backbonejs-snippets-view.coffee:5:3)
    at Object.<anonymous> (/Users/Laurent/.atom/packages/backbonejs-snippets/lib/backbonejs-snippets-view.coffee:1:1)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/Laurent/.atom/packages/backbonejs-snippets/lib/backbonejs-snippets.coffee:1:26)
    at Object.<anonymous> (/Users/Laurent/.atom/packages/backbonejs-snippets/lib/backbonejs-snippets.coffee:1:1)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:720:27)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:116:28
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at Package.module.exports.Package.load (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:106:12)
    at PackageManager.module.exports.PackageManager.loadPackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:445:14)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:524:30)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:444:29
    at exit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:73:16)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:220:18
    at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:98:18)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```

### Commands

```
     -9:34.1.0 tree-view:remove-project-folder (div.header.list-item)
     -9:27.7.0 settings-view:open (ul.list-inline.tab-bar.inset-panel)
     -8:41.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:47.9.0 application:new-file (div.panels)
     -0:24.7.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:16.2.0 core:backspace (atom-text-editor.editor.is-focused)
```

### Config

``` json
{
  "core": {}
}
```

### Installed Packages

``` coffee
# User
atom-backbone, v0.6.1
backbonejs-snippets, v0.4.1
minimap, v4.20.0

# Dev
No dev packages
```

**Comment by bartekpospiech** [comment]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.12.8
**Electron Version**: 1.3.13
**System**: Microsoft Windows 10 Pro
**Thrown From**: [backbonejs-snippets](https://github.com/d1b1/atom-backbonejs) package, v0.4.1


### Stack Trace

Failed to load the backbonejs-snippets package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at extend (file:///C:/Users/bartosz.pospiech/.atom/packages/backbonejs-snippets/lib/backbonejs-snippets-view.coffee:1:1)
    at file:///C:/Users/bartosz.pospiech/.atom/packages/backbonejs-snippets/lib/backbonejs-snippets-view.coffee:4:7
    at Object.<anonymous> (file:///C:/Users/bartosz.pospiech/.atom/packages/backbonejs-snippets/lib/backbonejs-snippets-view.coffee:19:11)
    at Object.<anonymous> (file:///C:/Users/bartosz.pospiech/.atom/packages/backbonejs-snippets/lib/backbonejs-snippets-view.coffee:1:1)
    at Module._compile (C:\Users\bartosz.pospiech\AppData\Local\atom\app-1.12.8\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.value [as .coffee] (C:\Users\bartosz.pospiech\AppData\Local\atom\app-1.12.8\resources\app.asar\src\compile-cache.js:201:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (C:\Users\bartosz.pospiech\AppData\Local\atom\app-1.12.8\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (file:///C:/Users/bartosz.pospiech/.atom/packages/backbonejs-snippets/lib/backbonejs-snippets.coffee:1:26)
    at Object.<anonymous> (file:///C:/Users/bartosz.pospiech/.atom/packages/backbonejs-snippets/lib/backbonejs-snippets.coffee:1:1)
    at Module._compile (C:\Users\bartosz.pospiech\AppData\Local\atom\app-1.12.8\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.value [as .coffee] (C:\Users\bartosz.pospiech\AppData\Local\atom\app-1.12.8\resources\app.asar\src\compile-cache.js:201:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (C:\Users\bartosz.pospiech\AppData\Local\atom\app-1.12.8\resources\app.asar\src\native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (C:\Users\bartosz.pospiech\AppData\Local\atom\app-1.12.8\resources\app.asar\src\package.js:747:27)
    at C:\Users\bartosz.pospiech\AppData\Local\atom\app-1.12.8\resources\app.asar\src\package.js:118:28
    at Package.module.exports.Package.measure (C:\Users\bartosz.pospiech\AppData\Local\atom\app-1.12.8\resources\app.asar\src\package.js:92:15)
    at Package.module.exports.Package.load (C:\Users\bartosz.pospiech\AppData\Local\atom\app-1.12.8\resources\app.asar\src\package.js:106:12)
    at PackageManager.module.exports.PackageManager.loadPackage (C:\Users\bartosz.pospiech\AppData\Local\atom\app-1.12.8\resources\app.asar\src\package-manager.js:468:14)
    at C:\Users\bartosz.pospiech\AppData\Local\atom\app-1.12.8\resources\app.asar\src\package-manager.js:412:19
    at Config.module.exports.Config.transact (C:\Users\bartosz.pospiech\AppData\Local\atom\app-1.12.8\resources\app.asar\src\config.js:312:16)
    at PackageManager.module.exports.PackageManager.loadPackages (C:\Users\bartosz.pospiech\AppData\Local\atom\app-1.12.8\resources\app.asar\src\package-manager.js:407:19)
    at C:\Users\bartosz.pospiech\AppData\Local\atom\app-1.12.8\resources\app.asar\src\atom-environment.js:772:28
```

### Commands

```
```

### Config

```json
{
  "core": {
    "telemetryConsent": "no"
  }
}
```

### Installed Packages

```coffee
# User
atom-backbone, v0.6.1 (inactive)
backbonejs-snippets, v0.4.1 (inactive)
css-snippets, v1.1.0 (inactive)
emmet, v2.4.3 (inactive)
underscorejs-snippets, v0.2.2 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.45.0 (inactive)
base16-tomorrow-dark-theme, v1.3.0 (inactive)
base16-tomorrow-light-theme, v1.3.0 (inactive)
one-dark-ui, v1.6.2 (inactive)
one-light-ui, v1.6.2 (inactive)
one-dark-syntax, v1.5.0 (inactive)
one-light-syntax, v1.5.0 (inactive)
solarized-dark-syntax, v1.0.5 (inactive)
solarized-light-syntax, v1.0.5 (inactive)
about, v1.7.0 (inactive)
archive-view, v0.62.0 (inactive)
autocomplete-atom-api, v0.10.0 (inactive)
autocomplete-css, v0.13.1 (inactive)
autocomplete-html, v0.7.2 (inactive)
autocomplete-plus, v2.31.4 (inactive)
autocomplete-snippets, v1.11.0 (inactive)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (inactive)
background-tips, v0.26.1 (inactive)
bookmarks, v0.42.0 (inactive)
bracket-matcher, v0.82.2 (inactive)
command-palette, v0.39.0 (inactive)
deprecation-cop, v0.54.1 (inactive)
dev-live-reload, v0.47.0 (inactive)
encoding-selector, v0.22.0 (inactive)
exception-reporting, v0.40.0 (inactive)
find-and-replace, v0.202.2 (inactive)
fuzzy-finder, v1.4.0 (inactive)
git-diff, v1.1.0 (inactive)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (inactive)
image-view, v0.60.0 (inactive)
incompatible-packages, v0.26.1 (inactive)
keybinding-resolver, v0.35.0 (inactive)
line-ending-selector, v0.5.0 (inactive)
link, v0.31.2 (inactive)
markdown-preview, v0.158.8 (inactive)
metrics, v1.1.2 (inactive)
notifications, v0.65.1 (inactive)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.1 (inactive)
settings-view, v0.243.1 (inactive)
snippets, v1.0.4 (inactive)
spell-check, v0.68.4 (inactive)
status-bar, v1.4.1 (inactive)
styleguide, v0.47.2 (inactive)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.0 (inactive)
timecop, v0.33.2 (inactive)
tree-view, v0.210.0 (inactive)
update-package-dependencies, v0.10.0 (inactive)
welcome, v0.35.1 (inactive)
whitespace, v0.35.0 (inactive)
wrap-guide, v0.38.2 (inactive)
language-c, v0.54.0 (inactive)
language-clojure, v0.22.1 (inactive)
language-coffee-script, v0.48.0 (inactive)
language-csharp, v0.13.0 (inactive)
language-css, v0.40.1 (inactive)
language-gfm, v0.88.0 (inactive)
language-git, v0.15.0 (inactive)
language-go, v0.43.0 (inactive)
language-html, v0.47.1 (inactive)
language-hyperlink, v0.16.1 (inactive)
language-java, v0.24.0 (inactive)
language-javascript, v0.122.0 (inactive)
language-json, v0.18.3 (inactive)
language-less, v0.29.6 (inactive)
language-make, v0.22.2 (inactive)
language-mustache, v0.13.0 (inactive)
language-objective-c, v0.15.1 (inactive)
language-perl, v0.37.0 (inactive)
language-php, v0.37.3 (inactive)
language-property-list, v0.8.0 (inactive)
language-python, v0.45.1 (inactive)
language-ruby, v0.70.2 (inactive)
language-ruby-on-rails, v0.25.1 (inactive)
language-sass, v0.57.0 (inactive)
language-shellscript, v0.23.0 (inactive)
language-source, v0.9.0 (inactive)
language-sql, v0.25.0 (inactive)
language-text, v0.7.1 (inactive)
language-todo, v0.29.1 (inactive)
language-toml, v0.18.1 (inactive)
language-xml, v0.34.12 (inactive)
language-yaml, v0.27.1 (inactive)

# Dev
No dev packages
```
